2018/11/29 09:56:07 [error] 7#7: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082", referrer: "http://192.168.3.253:8082/"
2018/11/29 09:56:21 [error] 7#7: *6 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/29 09:56:31 [error] 7#7: *6 open() "/usr/share/nginx/html/index.html" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /index.html HTTP/1.1", host: "192.168.3.253:8082"
2018/11/29 09:56:31 [error] 7#7: *6 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/29 09:56:55 [error] 7#7: *13 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 07:21:15 [error] 7#7: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082", referrer: "http://192.168.3.253:8082/"
2018/11/30 08:15:41 [error] 7#7: *26 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:15:42 [error] 7#7: *29 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:20:59 [error] 7#7: *44 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:29:42 [error] 7#7: *46 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:29:47 [error] 7#7: *63 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "192.168.3.253:8082"
2018/11/30 08:29:47 [error] 7#7: *63 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:51:52 [error] 7#7: *65 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:51:58 [error] 7#7: *68 connect() failed (113: Host is unreachable) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "192.168.3.253:8082"
2018/11/30 08:51:58 [error] 7#7: *68 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 08:56:39 [error] 7#7: *13 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:05:45 [error] 7#7: *15 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:05:46 [error] 7#7: *20 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:10:25 [error] 7#7: *24 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:11:55 [error] 7#7: *26 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:14:15 [error] 7#7: *28 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/11/30 09:14:37 [error] 7#7: *37 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/03 01:20:52 [error] 7#7: *39 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/03 01:59:53 [error] 7#7: *40 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/03 02:20:44 [error] 7#7: *41 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/03 02:57:37 [error] 7#7: *47 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/03 02:57:39 [error] 7#7: *50 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 02:34:48 [error] 7#7: *52 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 02:34:50 [error] 7#7: *55 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 02:37:31 [error] 7#7: *59 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.31, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 02:40:41 [error] 7#7: *62 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.31, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:38:27 [error] 6#6: *12 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:38:28 [error] 6#6: *15 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:42:43 [error] 7#7: *8 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:46:28 [error] 7#7: *25 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:53:06 [error] 7#7: *31 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:53:07 [error] 7#7: *34 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:54:18 [error] 7#7: *43 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 03:55:12 [error] 6#6: *14 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 05:54:58 [error] 7#7: *1 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 05:55:00 [error] 7#7: *10 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 07:59:44 [error] 7#7: *16 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/04 07:59:46 [error] 7#7: *19 open() "/usr/share/nginx/html/favicon.ico" failed (2: No such file or directory), client: 192.168.50.48, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "192.168.3.253:8082"
2018/12/05 09:17:33 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:17:38 [error] 8#8: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:28 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:29 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:29 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:29 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:29 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:30 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:30 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:31 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:31 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:31 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:32 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:32 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:32 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:33 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:19:33 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:22:43 [error] 7#7: *17 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "127.0.0.1"
2018/12/05 09:42:04 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:05 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:05 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:05 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:06 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:10 [error] 7#7: *19 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:30 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:42:36 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:03 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:04 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:04 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:04 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:05 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:43:06 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:46:28 [error] 7#7: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:48:19 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:48:19 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:48:19 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:48:19 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
2018/12/05 09:48:19 [error] 7#7: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.50.48, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "192.168.3.253:8082"
